sudo: false

language: ruby

rvm:
  - '1.9.3'
  - '2.1'
  - ruby-head

env:
  global:
    - FOO=bar
  matrix:
    - RAKE_TASK=echo
    - RAKE_TASK=foo

matrix:
  allow_failures:
    - rvm: ruby-head

script:
  - bundle exec rake $RAKE_TASK

services:
  - redis
  - elasticsearch

addons:
  postgresql:
    - '9.2'
    - '9.3'
