sudo: false

language: ruby

rvm:
  - '1.9.3'
  - '2.1'

env:
  global:
    - FOO=bar
  matrix:
    - RAKE_TASK=echo
    - RAKE_TASK=foo

script:
  - bundle exec rake $RAKE_TASK

services:
  - redis
  - elasticsearch
